language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
  - jdk_switcher use oraclejdk8
  - mvn clean install sonar:sonar
addons:
  sonarcloud:
    organization: "erudika"
    token:
      secure: "nkkJbWtMczX4Pp3bGzFBlhnp3sthghgBRAPKfnsMw3dNoD8fMbB1EyrXicme6wExB5wzht0NbYR3WCnB5iMq7qMeRCh7M/eG9ecyZPOiCl4rRcK1GKLLjnSTFTxG2tbDTSVf66UPcbwwtK/d5XX6dfHvd2GwyAV1OnPn0OzzAfhOa4IkKmL3hy/+z14t9x9H+pRhX8uJItVBJeFOoeKvOdGEWA1MfjYmSfF3mriULpONrMorN9ql60vs0qgLsli8l1/5P8n7y9sm0N7K+98PntItZfDgX+XNjRQP+0qM6jUziXCOyx+6Phly/QqTg33zkaZhGNRHkahLGdwrAzj6W+Cjtn2uSU+6wM4HJQjaRc/7Jc2/IAlRRhde/RCFyit2KHbXmL+rEoby8A+GWHxbcR8a/5625kgY+QD4bOY/6hmt1GF1yRxpQmCuI3cjLVjgt5sP+GZpoR1aDaUHdF5qap+zTeWxYbzNUHgQD/2U+lW4I+0pZAmqq2PUPdW49u2EM3qVxBF81RWa3Wh63RLUdqUqo2rwIXLcA3mDPLDvGJdMsGIy9seXTBof3boPBc8DA4CKYLJ2/euZFWzF/QlUPyT5ltl93dKxlaE4aKvsm/K9Xqt/3U7HWslPqOwA8yeEmRuYCSSrIvUQhycTE6mmHCQ95YVaNmkCk0h+ps1dcHo="
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04820972e9b664f3140c
    on_success: change
    on_failure: always
    on_start: never

